### ISSUE TITLE
Dashboard shows Blank

### ISSUE THREAD

**Issue by ziyadsv** [mixcore/mix.core#148]
### Expected behavior
Dashboard is showing Blank because of some angular Error.Am new in Developing Please instruct me step by step if anything i need to do up and running this error

**Comment by Smilefounder** [comment]
Hi @ziyadsv , thanks for trying Mixcore. Could you help start the installation process again with the "develop" branch here: https://github.com/mixcore/mix.core/tree/develop

And please refer this build guide here: https://docs.mixcore.org/docs/introduction#build-run

Feel free let us know if you still facing any issues.

**Comment by skywalkerisnull** [comment]
Can confirm this is still an issue in v1.0.0-alpha.2 tag and also develop branch

**Comment by skywalkerisnull** [comment]
@Smilefounder @nhathoang989 
I think this issue needs to be re-opened as it is still an issue in the latest dev versions.

**Comment by ziyadsv** [comment]
Issue is fixed

**Comment by skywalkerisnull** [comment]
@ziyadsv which branch are you building from?

**Comment by Smilefounder** [comment]
Thanks @ziyadsv for your confirmation. 
@skywalkerisnull could you help share with me the steps and can you open the chrome dev console then screen capture any issues there.

**Comment by skywalkerisnull** [comment]
I went to redo it this morning on the develop branch and could not build the develop:

```
docker-compose build
db uses an image, skipping
Building web
Step 1/18 : FROM node:10.16.3 AS node-env
 ---> a68faf70e589       
Step 2/18 : WORKDIR /app 
 ---> Using cache        
 ---> 3e1059be2072       
Step 3/18 : COPY src/. ./
 ---> 6d98f1b3f06d
Step 4/18 : WORKDIR /app/portal-app
 ---> Running in c7b498117115
Removing intermediate container c7b498117115
 ---> 90bff64c9f42
Step 5/18 : RUN npm install
 ---> Running in 08ff752a22a1
npm WARN saveError ENOENT: no such file or directory, open '/app/portal-app/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/app/portal-app/package.json'
npm WARN portal-app No description
npm WARN portal-app No repository field.
npm WARN portal-app No README data
npm WARN portal-app No license field.

up to date in 1.342s
found 0 vulnerabilities

Removing intermediate container 08ff752a22a1
 ---> bb9e82439123
Step 6/18 : RUN npm install gulp-cli -g
 ---> Running in c1cad486d437
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp-cli/bin/gulp.js
+ gulp-cli@2.2.0
added 237 packages from 156 contributors in 23.072s
Removing intermediate container c1cad486d437
 ---> 1a415cb1ce4f
Step 7/18 : RUN npm install gulp -D
 ---> Running in d4d507f44d00
npm WARN saveError ENOENT: no such file or directory, open '/app/portal-app/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/app/portal-app/package.json'
npm WARN portal-app No description
npm WARN portal-app No repository field.
npm WARN portal-app No README data
npm WARN portal-app No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ gulp@4.0.2
added 316 packages from 217 contributors and audited 6512 packages in 34.067s
found 0 vulnerabilities

Removing intermediate container d4d507f44d00
 ---> bdc34d1b8cc4
Step 8/18 : RUN gulp build
 ---> Running in 8ee7e65f534b
[00:17:50] No gulpfile found
ERROR: Service 'web' failed to build: The command '/bin/sh -c gulp build' returned a non-zero code: 1
```

**Comment by Smilefounder** [comment]
Hi @skywalkerisnull really thanks for the information. I didn't aware that you are using docker. Recently, we just split portal to separate repo here https://github.com/mixcore/mix.spa.portal 

However, I haven't setup the docket with new structure yet. Let me revise this week and keep you posted ASAP.

For now, you can use develop branch without build mix.spa.portal. as the latest code from portal has been built and commit to develop branch.
