### ISSUE TITLE
Init setup issue with MySQL

### ISSUE THREAD

**Issue by AlphaComposite** [mixcore/mix.core#186]
Clicking "Next" on the init page creates the tables in the MySQL database, but there's an error afterward and the script stops. 

Build the solution
Run the web project
Init pages loads
Enter data for the MySQL database in the form
Click "Connect" button
Receive "Server errors" message and the page stops

**Screenshots**
![image](https://user-images.githubusercontent.com/25360554/74712597-49c4fe00-51ec-11ea-90b3-0679d011bec5.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version [79.0.3945.130]

**Comment by AlphaComposite** [comment]
Any workarounds for how to get this running?

**Comment by Smilefounder** [comment]
Hi @AlphaComposite 

You can use MS SQL server for now. We are fixing the issue and might get back to you with the latest fix update by today. Will keep you posted.

**Comment by Smilefounder** [comment]
@AlphaComposite please use the latest commit here https://github.com/mixcore/mix.core/tree/develop and feel free let us know if the issue has been resovled.

**Comment by AlphaComposite** [comment]
I tried the develop branch and it worked fine.
