### ISSUE TITLE
Server Errors after the database was initialized

### ISSUE THREAD

**Issue by alexohneander** [mixcore/mix.core#188]
**Describe the bug**
In the initialization process I always get a "Server Error".
I have compiled the source on my computer and moved it to the server. 
All DLL's are present.
I use MySQL as database.
He can establish a connection to the database because the database has tables after the initialization process.

**Source version**
Pre-release v1.0.0-alpha.5 - ASP.Net Core 2.2

**Screenshots**
![Anmerkung 2020-02-24 154510](https://user-images.githubusercontent.com/1469954/75161858-c724cd00-571c-11ea-8131-650d5e06b9d7.png)

**Desktop:**
 - OS: Windows Server 2016
 - Browser Firefox
 - Version 74

**Comment by Smilefounder** [comment]
@N00D13 please help use the latest version from develop branch. As this issue has been resolved.

Apologise for the issue, this is caused by we are migrating the dotnet core version from 2.x to 3.x

Related issue https://github.com/mixcore/mix.core/issues/186
