### ISSUE TITLE
'Object reference ...' error on creating/editing post

### ISSUE THREAD

**Issue by moslem-hadi** [mixcore/mix.core#208]
Hi,
I just cloned the source code and ran it. I did 'Init steps' and went to portal panel. 
but when I want to create a "Post" in '/portal/post/create', there is a "Object reference not set to an instance of an object" error in "\src\Mix.Cms.Lib\ViewModels\MixPosts\UpdateViewModel.cs" file line 1076:

![er1](https://user-images.githubusercontent.com/9815699/76689441-29515d80-664b-11ea-886d-b1b3053e26be.PNG)

and if I fix it by checking null value, another error appear on line 1036:
![er2](https://user-images.githubusercontent.com/9815699/76689468-5ef64680-664b-11ea-8fd9-8f622301778a.PNG)

even if I select  a "Parent page"

whats the issue, and how can I fix it??

**Comment by Smilefounder** [comment]
@moslem-hady could you help let me know which branch you are using right now? is it develop or master.

**Comment by Smilefounder** [comment]
@moslem-hady could you help try the following steps then let us know the result? Also, please always use the latest code from develop branch as currently we have migrated to .net core v3 + MySQL and there are a lot of changes and migration.

1. Check if pages & modules has been installed successful during installation step
2. Turn off then on the system cache via "Portal App Setting" > General > Site Data Cache
![image](https://user-images.githubusercontent.com/3785721/76695903-63f0df80-66b7-11ea-8de8-a4cc7de6ff5b.png)

**Comment by moslem-hadi** [comment]
I'm using master branch.
pages and modules is installed.
I turned off "Site data cache", but same errors still exist.
I'll to try "develop" branch and let you know what happend.
thanks

**Comment by Smilefounder** [comment]
Thanks @moslem-hady please try again with develop branch then feel free let us know if you are still facing any issues.

**Comment by moslem-hadi** [comment]
I tried "develop" branch. same error. but there may be an issue with initializing database. I dont know.
I opened another issue about init steps.

**Comment by mtxxx** [comment]
Update/Create Page is throwing an exception on Save as well. Just open any page (Home for example) and click on Save button.

**Comment by Smilefounder** [comment]
Hi @moslem-hady , @mtxxx , our team have fixed many issues since then. Please try again and feel free let us know if you facing any other issues.
