### ISSUE TITLE
I cant pass init spet 3

### ISSUE THREAD

**Issue by moslem-hadi** [mixcore/mix.core#210]
When I'm trying to run and init new site, I stuck in step 3 (theme select).
code doesnt pass this part:
![er3](https://user-images.githubusercontent.com/9815699/76698941-753cea80-66bd-11ea-80c3-88f31fb86aca.PNG)
I had this issue before, but it was fixed after a few tries.
it doesnt even show an error. (before there was a timeOut error)
Im working on "develop" branch. using vs 2019 v16.4.5 and sql server v18.4

**Comment by Smilefounder** [comment]
Thanks @moslem-hady May I double-check if your dev machine is Mac or Windows? Our team trying to reproduce your issues from our side at the moment.

**Comment by moslem-hadi** [comment]
Im using windows 10

**Comment by Smilefounder** [comment]
Thanks @moslem-hady I will try to reproduce the issue from our side, with video recording then share with you soon. So you can also be knowing what steps are not fine from both sides. Will keep you posted.

**Comment by net4u** [comment]
Same issue here: Windows 10, MS Visual Studio 2019. I will try to publish on my IIS server, and come back with details after.

**Comment by Smilefounder** [comment]
@moslem-hady @net4u please try again with the following version:
https://github.com/mixcore/mix.core/releases/tag/v1.0.0-beta.0

**Comment by net4u** [comment]
For me it works like before:
![image](https://user-images.githubusercontent.com/255743/82652203-e2bd4800-9c25-11ea-90d2-c930886e75d5.png)

**Comment by net4u** [comment]
For me it does not rise error in visual studio, but just what you can see in printscreen.

**Comment by net4u** [comment]
OK, after a long time, it enter in dashboard. But it was about 10 minutes or more.

**Comment by Smilefounder** [comment]
Thanks @net4u , there is some loading time to load the default template files into the database. We are discussing internally to improve this kind of issue.
