### ISSUE TITLE
install error step 3

### ISSUE THREAD

**Issue by diegobeltran** [mixcore/mix.core#254]
error de conexion in step 3 ( create and login the portal)

**Comment by Smilefounder** [comment]
Hi @diegobeltran thanks for letting us know about the issue, we going to deploy another version later today to fix this kind of issue. Will keep you posted.

**Comment by Smilefounder** [comment]
@diegobeltran  please try again with the following version:
https://github.com/mixcore/mix.core/releases/tag/v1.0.0-beta.0
