### ISSUE TITLE
dev.mixcore.org returns error 503

### ISSUE THREAD

**Issue by dzoech** [mixcore/mix.core#260]
**Describe the bug**

STAG / Demo (https://dev.mixcore.org) returns error 503

**Comment by Smilefounder** [comment]
Hi @dzoech could you try again? Thanks for your issue report.
![image](https://user-images.githubusercontent.com/3785721/84728392-50f1f200-afbb-11ea-8a3a-6f6162350aa6.png)

Best regards.

**Comment by dzoech** [comment]
No, still doesn't work:

```
Service Unavailable
HTTP Error 503. The service is unavailable.
```

**Comment by Smilefounder** [comment]
Hi @dzoech , my bad. My browser still cache the PWA testing at the time I loaded the site so I thought it still work.

My team have fixed the link :) please take a look and feel free to ping us any times.
