### ISSUE TITLE
Cannot get past init screen

### ISSUE THREAD

**Issue by FelixStumvoll** [mixcore/mix.core#261]
**Describe the bug**
Im trying to start the cms with the docker-compose file and it starts but i cant get past the init screen.

When i press connect it loads for a bit and then i get the message _Server Errors Press Escape to dismiss_
![image](https://user-images.githubusercontent.com/22666794/84773668-0a14f400-afdd-11ea-8c66-b5bd47416bb0.png)

There isn't anything in the logs which indicates something

**To Reproduce**
1. clone
2. `docker-compose up`
3. insert db info
4. press next

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 84

**Comment by Smilefounder** [comment]
Hi @FelixStumvoll please help take a look at https://docs.docker.com/compose/networking/

We can not use localhost as it is internal docker network.

Explanation from the link above have mentioned this:

> Within the web container, your connection string to db would look like postgres://db:5432, and from the host machine, the connection string would look like postgres://{DOCKER_IP}:8001.

Please try again and feel free let me know if it working :)

**Comment by Smilefounder** [comment]
I have tried with Azure free instant and it should work with below config:

![image](https://user-images.githubusercontent.com/3785721/84776762-eec0dd80-b00a-11ea-8025-71cac499a490.png)

**Comment by Smilefounder** [comment]
Hi @FelixStumvoll fyi, I have created a quick note on how installed with Azure free instant here:
https://community.mixcore.org/topic/4/install-mixcore-cms-with-azure-and-docker-compose

Hope this help :)
