### ISSUE TITLE
Init: Server Error

### ISSUE THREAD

**Issue by WernerDS** [mixcore/mix.core#262]
**Describe the bug**
https://localhost:5001/init

**local database**
Server=(localdb)\MSSQLLocalDB;Initial Catalog=144-mix-cms.db;Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True

**Dotnet Version**
3.1.301

![Screenshot 2020-06-19 at 13 43 39 (3)](https://user-images.githubusercontent.com/13958753/85129247-109ca900-b233-11ea-8ed5-52e55dc9fd1c.png)

**Comment by Smilefounder** [comment]
Hi @WernerDS Could you help reconfirm if MS SQL Server Express has been installed in your environment?
