### ISSUE TITLE
Need a home page for the end user

### ISSUE THREAD

**Issue by kibria06cse** [mixcore/mix.core#264]
After running the app from VS, it is redirecting to localhost:5000. It is showing an empty page.

![image](https://user-images.githubusercontent.com/7090820/85939422-43335980-b937-11ea-8c27-e8cf2a475781.png)

It would be better if there is a home page for mixCore

**Comment by kibria06cse** [comment]
(y)

**Comment by Smilefounder** [comment]
Hi @kibria06cse sorry for our late response, you can refer to the sample theme here https://github.com/mixcore/mix.theme.mixcore-agency

Or you can pull dev branch instead, dev branch now using Simple Blog as default theme.

The basic of Mixcore CMS theme is Razor, you can refer to official docs from MS here:
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.1&tabs=visual-studio
