### ISSUE TITLE
Blank admin page

### ISSUE THREAD

**Issue by clvnong** [mixcore/mix.core#278]
Hi,
After done the step 3 and I get the blank page instead of admin page.
Please find the javascript error in the image below.

<img width="451" alt="Picture 3" src="https://user-images.githubusercontent.com/48722009/96086967-b1575880-0ef5-11eb-84b9-f9f4e8c216f2.png">

Regards,
Calvin Ong

**Comment by Smilefounder** [comment]
Hi @clvnong is it on dev brach? 

Quite strenght as I just completed the setup step yesterday during debug another issue for you. 

Let me check again.

**Comment by clvnong** [comment]
Hi Huy,
Yes, it was from dev-branch.

**Comment by Smilefounder** [comment]
Hi @clvnong ,

Sorry for my late response, I just tried the full process and record the video here for your reference.
https://youtu.be/-1e-OQB2lUg

Please feel free let me know if you have any other issues.

Best regards,
Huy Nguyen
