### ISSUE TITLE
Server Errors

### ISSUE THREAD

**Issue by can1871** [mixcore/mix.core#280]
![error](https://user-images.githubusercontent.com/53393674/98523179-abe7f680-2286-11eb-9689-0a8538e11cf2.JPG)

**Comment by Smilefounder** [comment]
Hi @can1871  Have you tried with Remote SQL Server instead of Local DB? Local DB is for SQLExpress that you must install locally.

**Comment by Smilefounder** [comment]
Close due to no response from @can1871

**Comment by biapar** [comment]
I tried. The error is still there.

**Comment by Smilefounder** [comment]
@biapar we have removed SQLExpress and replace with SQLite instead for localdb solution at the moment.

You can try again with Mixcore v1.0.0 here:
https://github.com/mixcore/mix.core/releases/tag/v1.0.0

**Comment by biapar** [comment]
I try, now! Very good!
