### ISSUE TITLE
Broken link to Admin demo on ReadMe

### ISSUE THREAD

**Issue by RedFeet** [mixcore/mix.core#281]
The link to the Admin demo on the GitHub's ReadMe page doesn't work:

 [https://mochahost.demo.mixcore.org/portal](https://mochahost.demo.mixcore.org/portal)

**Comment by Smilefounder** [comment]
Thanks @RedFeet , let me double check.

**Comment by Smilefounder** [comment]
@RedFeet  Fixed server IP. Kindly check again.
