### ISSUE TITLE
Cannot create new media

### ISSUE THREAD

**Issue by hldvuong** [mixcore/mix.core#285]
I using lasted master mixcore source (2020-12-11)

I try to upload a new file
type the title, description...

mixcore portal not work or save the file

the javascript error:
 Uncaught (in promise) TypeError: objData is undefined

error in file app-shared.min.js : line 5050

var _save = async function(objData, file){
            var url = this.prefixUrl + '/save';
            var fd = new FormData();
            var file =objData.mediaFile.file;

Please fixed !

**Comment by Smilefounder** [comment]
thanks @hldvuong 

@nhathoang989 kindly review again the issue.

**Comment by Smilefounder** [comment]
Fixed on the latest beta version.
