### ISSUE TITLE
Recheck _ViewImports.cshtml for RazorRuntimeCompilation

### ISSUE THREAD

**Issue by Smilefounder** [mixcore/mix.core#305]

**Comment by nhathoang989** [comment]
Following https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio

Conditionally enable runtime compilation in an existing project
Runtime compilation can be enabled such that it's only available for local development. Conditionally enabling in this manner ensures that the published output:

- Uses compiled views.
- Doesn't enable file watchers in production.

We cannot apply runtime compile for mixcore
