### ISSUE TITLE
Integrate with PostgreSQL & SQLite

### ISSUE THREAD

**Issue by Smilefounder** [mixcore/mix.core#308]
- [x] Init flow
- [x] Create post flow
- [x] Create module flow
- [x] Create MixDB flow

**Comment by Smilefounder** [comment]
Hi @truongtphat, kindly help support on this feature request. Please check with @nhathoang989 in case if you have any questions.

**Comment by biapar** [comment]
I like SQLite

**Comment by Smilefounder** [comment]
Hi @biapar SQLite already added in the latest Beta.9 release. Kindly try and have fun :)
