### ISSUE TITLE
Init step1 error: Invalid object name 'mix_culture'.

### ISSUE THREAD

**Issue by moslem-hadi** [mixcore/mix.core#309]
Hi, I just cloned '**master**' branch. run the project and in the installation proccess, in step 1, there was an error.
I think migrations aren't working for `MsSqlMixCmsContext`.
look at this image:
![image](https://user-images.githubusercontent.com/9815699/104133637-1c4fe880-539a-11eb-9809-77da55eb0153.png)

an error is thrown on line 50. with the message "Invalid object name 'mix_culture'."
tables of 'accountContext' and 'messengerContext' seems to be created.
I also tried "**Pre-release v1.0.0-beta.7**". same error.
I'm using sql server 2019, and visual studio 2019 on windows 10
connection string example:
`Data Source=.;Initial Catalog=2277-mix-cms;Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True`
 
how can I fix it? what am I ding wrong?
thanks in advance

**Comment by Smilefounder** [comment]
Thanks @moslem-hady for the information. This issue has been fixed on Develop branch. We are testing some rounds before merge into master again soon.

**Comment by aimanhub** [comment]
I have the same issue "Invalid object name 'mix_culture'"
