### ISSUE TITLE
No Content Body Box

### ISSUE THREAD

**Issue by scyth666** [mixcore/mix.core#310]
Hi,
I try to install the latest release, but i could not connect to the Database. So i tryed to use the Developer Version and this Version i could install without issue. 
After that i wanted to create a new Post or Page, but for some reason i only can create the name and the excerpt and dont have a body box.
Here a Picture:
![grafik](https://user-images.githubusercontent.com/77341493/104335502-b5dedd80-54f3-11eb-9eab-9d7d65f1d742.png)

**Comment by Smilefounder** [comment]
Hi @scyth666 sorry for the issue, as we going to remove jQuery from our source completely and trumbowyg editor is mainly built on top of jQuery so we going to switch to quilljs instead. And will fix the issue within this week,

You can use the following branch for the stable version:
https://github.com/mixcore/mix.core/tree/LTS/dotnet-core-v3.x

**Comment by Smilefounder** [comment]
Fixed with commit https://github.com/mixcore/mix.core/commit/849d923cf230906c6b777f28cd7cabc27f58d76f

![image](https://user-images.githubusercontent.com/3785721/104562809-6b886880-567b-11eb-93a5-323b9a5cd516.png)

cc @scyth666
