### ISSUE TITLE
invalid object name 'mix_culture'

### ISSUE THREAD

**Issue by aimanhub** [mixcore/mix.core#312]
I download master branch, and run the code always getting error "invalid object name 'mix_culture'" when connect to MSSQL remote server

**Comment by tjansevanvuuren** [comment]
> I download master branch, and run the code always getting error "invalid object name 'mix_culture'" when connect to MSSQL remote server

I have the same issue and after debugging its almost like the MSSQL Migrations don't run. Tables for Messenger and Account are created by non of the Cms tables.

**Comment by Smilefounder** [comment]
Hi @aimanhub , @tjansevanvuuren ,

Please use the latest commit here https://github.com/mixcore/mix.core/commit/a93b876695a4eb517015ceec45d6c1f8cb29b20c and let us know the status. All of the issues should be fixed with this latest version.

Cheers!

**Comment by tjansevanvuuren** [comment]
Good day,

The MSSQL issue has been resolved, there is a shared context issue that may become a problem where the context has changed instance and doesn’t release it. If it pops up again Ill give you a shout.
