### ISSUE TITLE
Record Tracking.

### ISSUE THREAD

**Issue by tjansevanvuuren** [mixcore/mix.core#318]
**Describe the bug**
On various items (Pages, Posts and Modules the record tracking gets stuck)

**To Reproduce**
1. Write a post and add Images.
2. Save the post and preview
3. Change the post to have a parent or any values.
4. Click Save

**Git branch or source version**
Beta 8

**Expected behavior**
Be able to Edit the post or Item

**Screenshots**
![image](https://user-images.githubusercontent.com/72187714/105835195-2d246f00-5fd4-11eb-991b-f49394998bb4.png)

**Comment by Smilefounder** [comment]
Hi @tjansevanvuuren Could you try again with the Master branch? It should be fixed.

Thanks.

**Comment by Smilefounder** [comment]
Hi @tjansevanvuuren kindly use the latest pre-release version here https://github.com/mixcore/mix.core/releases/tag/v1.0.0-beta.9 then let us know if the issue still remain.
