### ISSUE TITLE
Site Error in Step 1 - Pre-release v1.0.0-beta.7 

### ISSUE THREAD

**Issue by biapar** [mixcore/mix.core#319]
In Pre-release v1.0.0-beta.7 the system give Server Error.
I try to install on local SQL Server. The wizard install a part of db.

**Comment by Smilefounder** [comment]
Hi @biapar kindly try again with the latest pre-release version here https://github.com/mixcore/mix.core/releases/tag/v1.0.0-beta.9 and let us know if the issue still remains.

**Comment by biapar** [comment]
But the  9th version is on .NET Core 5.
PS: the link doesn't exist.

**Comment by Smilefounder** [comment]
Hi @biapar We would recommend .NET Core 5 as it is more stable with a bunch of security updates.
Kindly use the link again here https://github.com/mixcore/mix.core/releases/tag/v1.0.0-beta.9

Btw, you can .NET Core v3 here https://github.com/mixcore/mix.core/tree/LTS/dotnet-core-v3.x for latest code/fixing issues.
