### ISSUE TITLE
Content is not display after creating a page.

### ISSUE THREAD

**Issue by NagarRahul** [mixcore/mix.core#323]
**Describe the bug**

**To Reproduce**

**Git branch or source version**
developer or master...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Smilefounder** [comment]
Hi @NagarRahul 

You can add the following line into the _Blank template:
Content: @Model.Content
![image](https://user-images.githubusercontent.com/3785721/106723847-1fa55f80-663a-11eb-99da-99da25eeaea4.png)

Thanks.
