### ISSUE TITLE
I can not add new Database 

### ISSUE THREAD

**Issue by ali-alhuwswe** [mixcore/mix.core#332]
I just install new mix core but when i try to add new database from the contrl panle i am getting this error 

"Cannot insert the value NULL into column 'Name', table 'mixcore.dbo.mix_attribute_set'; column does not allow nulls. INSERT fails. The statement has been terminated."

![Capture2](https://user-images.githubusercontent.com/62011312/107121843-a316b900-68a5-11eb-9972-20b9d58b4082.PNG)

**Comment by ali-alhuwswe** [comment]
I can help if someone give me a breve about the code

**Comment by Smilefounder** [comment]
Hi @ali-alhuwswe thanks for your help. Im working on the documentation at the moment. Btw, which version that you are using and having the issue? Kindly ise develop branch and let us know if the issue has been resolved? As we are try to cleaning the source code at the moment.

**Comment by ali-alhuwswe** [comment]
Hi @Smilefounder after 2 hours of debugging i solve it i will make a branch and contribute

**Comment by ali-alhuwswe** [comment]
I notice it is fixed in develop branch but in the master it is not

**Comment by Smilefounder** [comment]
Thanks @ali-alhuwswe ! You are super fast! Thanks a lot for your support so far. Kindly let us know if you facing any trouble or concern with Mixcore. Any help/support from you is really helpful!!! <3

I will close this ticket, for now, feel free create any other tickets during using Mix
