### ISSUE TITLE
Run on Apple macOS BigSur

### ISSUE THREAD

**Issue by biapar** [mixcore/mix.core#347]
![image](https://user-images.githubusercontent.com/661517/107927426-4d15d580-6f77-11eb-888f-3e099c2f977c.png)

**Comment by Smilefounder** [comment]
Hi @biapar could you help explain more detail on the issue? Are you able to click on the navigations?

**Comment by biapar** [comment]
Yes..it's all ok. I tried to compile from source and goes.
