### ISSUE TITLE
Save Module/Page/Post for multi languages isn't working.

### ISSUE THREAD

**Issue by UmerTariqKhan** [mixcore/mix.core#458]
When I create a module or page, and go to languages and select both defined languages and save, it is only created for a specific language. Please see attached file. 

Thanks
[multi-language-content.zip](https://github.com/mixcore/mix.core/files/6941107/multi-language-content.zip)

**Comment by nhathoang989** [comment]
Fixed https://github.com/mixcore/mix.core/pull/461
