### ISSUE TITLE
Questons - Markdown and Headless?

### ISSUE THREAD

**Issue by dotnetshadow** [mixcore/mix.core#46]
Hi there,

Great work on this project. I'm interested in knowing a little more about this project. 

1. Do the posts / content support markdown? 
2. Can this be used like a headless CMS? 
    I was wondering if it would be possible to be able to use the headless api side in an older asp.net mvc5 app ?
3. Is there any documentation on how to add this to an existing asp.net core application with layout.cshtml?

**Comment by Smilefounder** [comment]
Hi @dotnetshadow ,

Thanks for reaching us. Please see my team response here:

1. Do the posts / content support markdown?
-> Not yet. However, this is in our TODO list. 

2. Can this be used like a headless CMS?
-> Yes, it is. We have 2 API section. 1 for CMS itself and 1 for 3rd services. 
- For CMS itself, we are using a customized API method of MVC from .NET core.
- For 3rd services, we are applying https://www.odata.org 

3. Is there any documentation on how to add this to an existing asp.net core application with layout.cshtml?
-> Yes, we have. However, it is still in progress and still lacking many core explanation. We are trying our best to make it fully asap. Please keep visit from here: https://docs.mixcore.org

Best regards,
Huy Nguyen

**Comment by Smilefounder** [comment]
Hi @dotnetshadow , we have applied markdown editor and Odata to the CMS. The document is on the way.

Best regards,
Mixcore Team.
