### ISSUE TITLE
Cannot use provided themes

### ISSUE THREAD

**Issue by LeandroMendesDS** [mixcore/mix.core#536]
**The bug**
Everytime i try to dowload one of the provided themes i get an error!
This happens in the inital setup and in the theme dashboard asweell

**Expected behavior**
Download and use a provided theme

**Screenshots**
![image](https://user-images.githubusercontent.com/78216924/138458580-b6ad2110-fd3d-4169-9001-142e2d03d4fe.png)

**Desktop:**
 - OS: Windows 10
 - Browser : Edge
 - Version Version 94.0.992.50 (Official build) (64-bit)

**Comment by nhathoang989** [comment]
Hi, @LeandroMendesDS . I just tested the newest code from master and it works well.
Which version are you using?

**Comment by LeandroMendesDS** [comment]
Latest from master branch.
Followed the instructions on the git repository . Cloned the project and tried to setup and got the error on themes dowload

Also tried to use the zip instead of the full source code.... only run the zip file on IIS everything goes smooth and i cant also dowload themes

**Comment by nhathoang989** [comment]
I think there are some issues with your database. which database are you using? Try to drop and run again. 
I tried with sqlite and it work well

https://webm.red/LnQp

**Comment by LeandroMendesDS** [comment]
Im using Microsoft SQL Server , please retest if you can with that sql type.  I tried creating and azure instance db aswell the same error occurs. Other people said the same using microsoft sql server.

**Comment by nhathoang989** [comment]
I tested it with sqlserver and it worked. https://webm.red/ggzU 

However, there is a problem with the reference to Mix.Heart, I switched it from a local reference to a nuget package.

Please try again after downloading the latest source code.

**Comment by LeandroMendesDS** [comment]
Hey! That was probably the problem . Latest source code doesn't throw the same error anymore and i can successfully download a theme.
Thanks for the quick fix.

**Comment by nhathoang989** [comment]
Glad to hear that !
