### ISSUE TITLE
Material KIT Pro components not working

### ISSUE THREAD

**Issue by LeandroMendesDS** [mixcore/mix.core#539]
**Describe the bug**
Material KIT Pro components not working. As it states only normal non pro components if you try to use an carousel or accordion it simple doesn't render in my testing. 
As mixcore advertises the usage of material kit pro i was trying to understand if its bug or what we really have it the normal non pro version

**To Reproduce**
-Use Marked pro components from the material kit template 
[https://www.creative-tim.com/learning-lab/bootstrap/collapse/material-kit](url)

**Git branch or source version**
master

**Expected behavior**
Usage of material kit ui pro components at its the one stated as the usable version

**Screenshots**
![image](https://user-images.githubusercontent.com/78216924/138917595-c3571ba2-cd08-41bc-b728-ebf1b79fc8b2.png)

**Comment by Smilefounder** [comment]
Hi @LeandroMendesDS as my team didn't purchased the Material KIT Pro and the Material Kit theme for Mixcore CMS is based on the free version. So Pro components can not be used. So sorry for the confusion.

According to Mixcore CMS architect, it should work with any kinds of themes based on Razor template structure. So i think it is because the theme's js files not loading properly. or placed in the wrong place.

**Comment by LeandroMendesDS** [comment]
i think its just a case of miss understanding .    In the theme section if you click the link its redirects to the pro components so i thought the cms used those when choosing material kit.   But since we are in the topic which files should be selected when choosing a custom theme input file?

**Comment by Smilefounder** [comment]
> In the theme section if you click the link its redirects to the pro components so i thought the cms used those when choosing material kit.

Yes, it is our bad. We copied the wrong description from Creative Tim site.

> But since we are in the topic which files should be selected when choosing a custom theme input file?

Actually, only the zip file that exported from Mixcore CMS can be imported. This is mean that once you done the theme setup, then you can export it to upload to our theme store (WIP), or yo can import to another sites during install steps.

![image](https://user-images.githubusercontent.com/3785721/138922147-51079111-35b0-4d76-915c-55fe1d1a28b0.png)
