### ISSUE TITLE
Binding warnings in container output

### ISSUE THREAD

**Issue by mrtasci** [mixcore/mix.core#544]
Unable to run Mixcore as docker container. There is binding warnings in container output.  

_warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Cannot assign requested address'.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to https://localhost:5001 on the IPv6 loopback interface: 'Cannot assign requested address'._

**To Reproduce**
Open terminal and run following commands:
`docker pull mixcore/mix.core:latest`
`docker run -it --rm -p 5000:80 --name mixcore_cms mixcore/mix.core:latest`

OS: Mac OS Monterey 12.0.1

**Comment by Smilefounder** [comment]
@mrtasci could you help check again to see if there is any other app that already run with 5000/5001 ports?

**Comment by Smilefounder** [comment]
@mrtasci I just tried from my side and it is fine. Please try again with the latest docker image from master.

![image](https://user-images.githubusercontent.com/3785721/141236869-0215eb64-fcc4-481e-ac44-3295d0444558.png)

**Comment by mrtasci** [comment]
@Smilefounder I can see same warning in your screen shot. Are you able to browse the site by http://localhost:5000?

**Comment by Smilefounder** [comment]
@mrtasci we have updated the docker file to make it work properly. However, the Docker HUB (free package) can not sync the latest dockerfile at the moment.
![image](https://user-images.githubusercontent.com/3785721/141324995-43fcaf62-a27a-4eb3-8be9-bdcba96c2c76.png)

**Comment by nhathoang989** [comment]
Hi @mrtasci , you can try this
docker run -it --rm -p 127.0.0.1:5000:80 --name mixcore_cms -e ASPNETCORE_URLS=http://+:80 mixcore/mix.core:latest

**Comment by mrtasci** [comment]
@nhathoang989  I just tried with the command you mentioned. It seems it started properly but I am not able to browse site by http://127.0.0.1:5000 
There is a runtime error. I've got HTTP 500 from http://127.0.0.1:5000/init page.
<img width="1442" alt="Screen Shot 2021-11-12 at 08 25 39" src="https://user-images.githubusercontent.com/1313511/141414642-b6920654-232c-4c47-b551-89868ea82638.png">

**Comment by Smilefounder** [comment]
@mrtasci could you also help to try with docker IP?

**Comment by nhathoang989** [comment]
There is a problem with razor while updating to Net 6. The views.dll file is now missing.
Please try again after updating mixcore/mix.core:latest.

**Comment by mrtasci** [comment]
@nhathoang989 It worked now with latest image and below command. I am able to browse the site by http://localhost:5000/ . Thank you!

`docker run -it --rm -p 5000:80 --name mixcore_cms -e ASPNETCORE_URLS=http://+:80 mixcore/mix.core:latest`
