### ISSUE TITLE
The interface cannot download the theme data, causing the page to have no buttons

### ISSUE THREAD

**Issue by Pacteraed** [mixcore/mix.core#554]
The local interface "https://store.mixcore.org/api/" cannot be accessed across domains, and the page buttons cannot be displayed

**Comment by Smilefounder** [comment]
Thanks @Pacteraed the issue has been fixed from the store side. Kindly reconfirm again.

**Comment by Pacteraed** [comment]
OK, I tried it and it has been solved. Thank you for your support.
