### ISSUE TITLE
data in mixdb single table is not in sync with mix_database_data_value

### ISSUE THREAD

**Issue by drajar** [mixcore/mix.core#606]
I created a MixDatabase with name test with two Text columns Name and Description and migrate to single table from portal.
Generated db table: mixdb_test_en_us
First observation is that the name contain lang/culture. I think is not ok. The name must be mixdb_test.

Added sample data from portal (Name1, Description1). The data is in mix_database_data_value but not in mixdb_test_en_us.

If I migrate to single table again...the mixdb_test_en_us is dropped and recreated...

The same scenario is true for add, change, delete data.

So, I think that the name of generated table must not contain culture. The specificculture from table is sufficient.
Second, if migrated to single table, all data must be storred in mixdb_test and not in mix_database_data_value and don't think that drop and recreate is a good ideea. I can have fk for example.

**Comment by Smilefounder** [comment]
Thanks @drajar let me check with the team and get back to you asap.

Btw, which branch or version you are using now?

**Comment by drajar** [comment]
master branch; database is mariadb, but don't think that mater.

**Comment by Smilefounder** [comment]
Hi @drajar sorry for have you confusing, DB migration feature for v1 is not ready yet, I thought the CTA was hide. Please ignore this feature on v1. We have decided to stop working on this feature on v1 and will implement for v2 asap.

Btw, the speed of the cache system already fast enough, you don't needs to use this kind of feature for normal site. We have planned for super enterprise system in the future but we don't have enough time to work on yet.

**Comment by Smilefounder** [comment]
Hide DB Migration Feature. https://github.com/mixcore/mix.core/pull/607
