### ISSUE TITLE
Cannot install any theme at initialisation

### ISSUE THREAD

**Issue by Forgh** [mixcore/mix.core#620]
**Describe the bug**
During the init sequence (step 3), I have been unable to install any theme. The theme seems to download just fine but the installation fails after a few seconds, without any log in the JS console nor the docker console. 
2 errors appears on the screen (see screenshot below) stating "Cannot install theme" and "Object reference not set to an instance of an object".
The network tab displays a HTTP 400 error on http://localhost:5000/api/v1/rest/theme/portal/install : Object reference not set to an instance of an object.

**To Reproduce**
1. docker-compose build
2. docker-compose up
3. Go to localhost:5000/
4. Fill up the form for /step1 with the connection settings for a sql server database (on Azure, I can see the tables in the database)
5. Fill up the form for /step2 for the admin user
6. Install any theme from the mixcore store on /step3

**Git branch or source version**
master (b4f9c3645cde28287dd2d1b25ac1c448ee8819ce)
Also tried the :latest image from Docker hub (even though it is outdated) with the same result

**Expected behavior**
Installation should succeed and let me proceed to the next step.

**Screenshots**
![image](https://user-images.githubusercontent.com/8050221/168998716-fbb4e41b-e9f2-4b7e-9d67-073f25e0c016.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 78.11.0esr (64 bits)
 - Version: v1.0.7 (commit b4f9c3645cde28287dd2d1b25ac1c448ee8819ce)

**Additional context**
Also tried the :latest image from Docker hub (even though it is outdated) with the same result

**Comment by Smilefounder** [comment]
@Forgh apologize for the issue. I haven't maintained the docker file properly for at least 6 months. Look like the latest docker image quite old. Let me review and fix asap.

At the moment, please try to run the release directly by running the mixcore.exe file if you would love to try the CMS.

**Comment by Smilefounder** [comment]
@Forgh please try the following package and let us know if you have any other issues. Btw, you should delete the existing DB or create a new DB to start init the CMS again
```
docker pull ghcr.io/mixcore/mix.core:master
```

**Comment by Smilefounder** [comment]
Close with #626
