### ISSUE TITLE
Error during initialisation (DDL Statement for database rendered incorrectly)

### ISSUE THREAD

**Issue by sudoku-committer** [mixcore/mix.core#626]
**Describe the bug**
I have encountered a bug where creating a user, database in Init - Mixcore starting page produces an error, which shows 'server errors'. After digging deeper figured that sql statement for creating cached settings instance is rendered incorrectly. See below..

**To Reproduce**
1. docker-compose up [docker-compose.txt](https://github.com/mixcore/mix.core/files/8912157/docker-compose.txt)
2. setup a user in db service [https://stackoverflow.com/questions/30641512/create-database-from-command-line](user)
3. go to and fill in info: http://localhost:5000/init
4. line with Value rendered ddl incorrectly:
``` pub-db-1       | 2022-06-15 21:23:25.683 UTC [83] ERROR:  type "ntext" does not exist at character 70
pub-db-1       | 2022-06-15 21:23:25.683 UTC [83] STATEMENT:  CREATE TABLE mix_cache (
pub-db-1       |            "Id" varchar(150) NOT NULL,
pub-db-1       |            "Value" ntext NOT NULL,
pub-db-1       |            "ExpiredDateTime" datetime NULL,
pub-db-1       |            "ModifiedBy" varchar(50) NULL,
pub-db-1       |            "CreatedBy" varchar(50) NULL,
pub-db-1       |            "LastModified" datetime NULL,
pub-db-1       |            "CreatedDateTime" datetime NOT NULL,
pub-db-1       |            "Priority" int NOT NULL,
pub-db-1       |            "Status" varchar(50) NOT NULL,
pub-db-1       |            CONSTRAINT "PK_mix_cache" PRIMARY KEY ("Id")
pub-db-1       |        )
```

**Git branch or source version**
[master](https://github.com/mixcore/mix.core/blob/master/docker-compose.yml)

**Expected behavior**
Expected to setup database and user.

**Desktop (please complete the following information):**
 - host - Archlinux, OS - Docker

 - Mozilla Firefox
 - 101.0 (64-bit)

**Comment by Smilefounder** [comment]
Thanks @lithiferous let me check asap!

**Comment by Smilefounder** [comment]
@lithiferous please try the following package and let us know if you have any other issues. Btw, you should delete the existing DB or create a new DB to start init the CMS again
```
docker pull ghcr.io/mixcore/mix.core:master
```

**Comment by sudoku-committer** [comment]
@Smilefounder Package works without problems, thx for your help!

**Comment by Smilefounder** [comment]
Thanks @lithiferous for the reconfirm
