### ISSUE TITLE
Error converting value \"GuidAdditionalData\" to type 'Mix.Constant.Enums.MixDatabaseType'. Path 'mixDatabases[0].type', line 1, position 2413."

### ISSUE THREAD

**Issue by tienoho** [mixcore/mix.core#643]
**Describe the bug**
In the installation step : /init/step4
when running the api : /api/v2/rest/mix-tenancy/setup/load-theme
Show error:
Error converting value \"GuidAdditionalData\" to type 'Mix.Constant.Enums.MixDatabaseType'. Path 'mixDatabases[0].type', line 1, position 2413."

**Git branch or source version**
Mixcore v2.0.0-alpha.1

**Screenshots**
![error](https://user-images.githubusercontent.com/25219790/197401006-a81f78f2-5cb9-4e09-b86c-6bddba35c9d4.png)

**Information:**
 - Database : PostgreSQL
 - Browser: chrome

**Comment by nhathoang989** [comment]
Hi @tienoho , 
Please delete the MixContent folder and try again. 
There's a mistake when we try to update the newer package to the store.
Thank you for reporting this issue

**Comment by tienoho** [comment]
> Hi @tienoho , Please delete the MixContent folder and try again. There's a mistake when we try to update the newer package to the store. Thank you for reporting this issue

okay sếp ✌️
