### ISSUE TITLE
Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone', consider using 'timestamp with time zone'. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior

### ISSUE THREAD

**Issue by tienoho** [mixcore/mix.core#644]
**Describe the bug**
In the installation step : /init/step3
when running download theme

Show error:
"Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone', consider using 'timestamp with time zone'. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior"

Fix error:
Project : Mix.Cms.Lib
Models -> Cms -> _MixCmsContext.cs
Function: **OnModelCreating**

Insert 
**
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", true);
**
After code: **case MixDatabaseProvider.PostgreSQL**

**Git branch or source version**
Mixcore v2.0.0-alpha.1

**Information:**
 - Database : PostgreSQL
 - Browser: chrome

**Comment by truongtphat** [comment]
We have fixed this issue. #656. This issue will be closed.
