### ISSUE TITLE
Mysql 8: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uuid()' at line 1

### ISSUE THREAD

**Issue by toanlcgift** [mixcore/mix.core#649]
**Describe the bug**

`"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uuid()' at line 1"`

**To Reproduce**
1. Go to Setup
2. Submit new admin account.

**Git branch or source version**

mixcore-v2.0.0-alpha.1

**Expected behavior**
setup successful

**Screenshots**
![image](https://user-images.githubusercontent.com/12400049/204434552-4f7ee5ce-42f5-40a2-a7dd-3cba410945d7.png)

**Additional context**
Mysql 8

Your MySQL connection id is 7801
Server version: 8.0.21 MySQL Community Server - GPL

![image](https://user-images.githubusercontent.com/12400049/204435223-81293cfe-229d-4410-be1f-07452ba80578.png)

refer: https://stackoverflow.com/questions/46134550/mysql-set-default-id-uuid

**Comment by nhathoang989** [comment]
Hi @toanlcgift ,
This bug was fixed in develop.
We're going to release a new version as soon as possible.
