### ISSUE TITLE
Internal Server Error Swagger

### ISSUE THREAD

**Issue by mokarchi** [mixcore/mix.core#660]
**Describe the bug**
Internal Server Error Swagger 

**To Reproduce**
1. Go to 'https://v2.dev.mixcore.org/api/v2/mixcore/swagger/index.html '
2. Click on swagger demo
3. See error qliteException: SQLite Error 14: 'unable to open database file'.

**Comment by Smilefounder** [comment]
Thanks @mokarchi for the bug report. v2 on our domain quite out of date. @nhathoang989 from our team will deploy the latest version again asap. Will keep you posted.

**Comment by Smilefounder** [comment]
The link should be working now. Kindly reconfirm. Thanks.

**Comment by mokarchi** [comment]
Thanks
