### ISSUE TITLE
Cannot Switch to 'develop' Branch

### ISSUE THREAD

**Issue by burakdobur** [mixcore/mix.core#667]
**Describe the bug**
Cannot switch to development branch

**To Reproduce**
> git switch -c develop origin/develop
```
Updating files: 100% (4036/4036), done.
fatal: not a git repository: src/platform/core/mix-heart/../../../../.git/modules/src/platform/core/mix-heart
```

**Git branch or source version**
master

**Expected behavior**
git switch command should switch.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Git Version: git version 2.39.1.windows.1

When I download 2.0-alpha the solution is missing Mix.Heart project and could not be compiled in Visual Studio.
When I download the zip it's still missing the Mix.Heart project. 

How can we use this 2.0 branch with source code, not the pre-built assembly?

**Comment by Smilefounder** [comment]
@burakdobur please use --recursive to pull the submodule as well.
```
git clone --recursive...
```
