### ISSUE TITLE
Build bản v2 đang bị lỗi

### ISSUE THREAD

**Issue by sonhoang23** [mixcore/mix.core#680]
**Describe the bug**
Dear các anh contributor

Hiện em build bản commit mới nhất 06e5610a671e65ffe5373d613d04ae093ba50431 đang gặp một số lỗi build như thiếu using (IMixCmsService line 44 file SharedApiController.cs) 
hoặc line 568 file MixDbController.cs đang chưa define
em đã import mix,heart project vào solution, rebuil nhiều lần nhưng vẫn lỗi

không rõ là do em pull thiếu code hay lý do nào khác, mong các anh reply.

trân trọng,

**Comment by Smilefounder** [comment]
Hi em @sonhoang23 ,

Không biết em đã chạy lệnh:
```
git submodule update --init --recursive
```
Để pull submodule liên quan chưa?

**Comment by sonhoang23** [comment]
Dạ em chưa,

Cảm ơn anh đã phản hồi ạ

**Comment by Smilefounder** [comment]
Trong readme bên branch dev có ghi chú phần này:
https://github.com/mixcore/mix.core/tree/develop

Em thử lại nhé. Anh tạm close issue.

**Comment by sonhoang23** [comment]
Dear các anh,
Em đã check lại bản commit mới nhất và pull cả sub project vẫn lỗi

Lỗi này là do syntax do chưa define

Em có check từ commit b13103e trở về trước build và run lên được ạ

**Comment by Smilefounder** [comment]
@nhathoang989 @truongtphat kindly help.

**Comment by Smilefounder** [comment]
@sonhoang23 em pull latest develop về thử lại nhé

**Comment by sonhoang23** [comment]
many thanks!
