### ISSUE TITLE
Step Intit call login api instead of register

### ISSUE THREAD

**Issue by sonhoang23** [mixcore/mix.core#681]
**Describe the bug**
Dear các anh,

Sau khi pull lastest commit về, đã build và run thành công
nhưng đến step thứ 2 (sau khi register database provider) nhập user, pw => call đến api login thay vì api register
Theo em hiểu bước này mình sẽ create accout for admin chứ không phải login

trân trọng

**Screenshots**
![image](https://github.com/mixcore/mix.core/assets/42433854/8cec4cab-6cfc-48c4-b1a0-5c69356dae33)

**Comment by Smilefounder** [comment]
Ah sau khi create thì sẽ auto login và redirect vô admin dashboard đó @sonhoang23. Còn lỗi chắc do merge lên chưa đủ

@nhathoang989 @truongtphat fyi

**Comment by truongtphat** [comment]
Hi @sonhoang23, 
I cannot reproduce your issue. Please help to delete `src/applications/Mixcore/mixcontent` folder and try starting it again.

**Comment by sonhoang23** [comment]
Many thanks!

I leaved out init-account api, i try to debug and the reason that is password to short.
I think we need additional notification.

**Comment by truongtphat** [comment]
Thanks for your feedback.
