### ISSUE TITLE
Adding <i> </i> with any Favicon icon and its automatically creating <SVG> tags.

### ISSUE THREAD

**Issue by arpit1188** [mixcore/mix.core#709]
Hello, 

Here, In the Trumbowyg editor of project getting some issue. 

Actually when I am trying to add code this in source code:
``````````````````````````````````````````````````````````````````````````````````````
<p>hello</p><p><br></p>

<label class="click_aerrow">
     <i class="fa fa-angle-down"></i> 
</label>
``````````````````````````````````````````````````````````````````````````````````````

it's Automatically converting this code later with SVG tags like below:
``````````````````````````````````````````````````````````````````````````````````````
<p>hello</p><p><br></p>

<label class="click_aerrow">
     <svg class="svg-inline--fa fa-angle-down fa-w-10" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="angle-down" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" data-fa-i2svg=""><path fill="currentColor" d="M143 352.3L7 216.3c-9.4-9.4-9.4-24.6 0-33.9l22.6-22.6c9.4-9.4 24.6-9.4 33.9 0l96.4 96.4 96.4-96.4c9.4-9.4 24.6-9.4 33.9 0l22.6 22.6c9.4 9.4 9.4 24.6 0 33.9l-136 136c-9.2 9.4-24.4 9.4-33.8 0z"></path></svg><!-- <i class="fa fa-angle-down"></i> --> 
</label>
``````````````````````````````````````````````````````````````````````````````````````

I don't want to use SVGs in my code. so any ways I can stop this ?

**Comment by arpit1188** [comment]
This what exactly happening with me :
https://www.loom.com/share/36afbd2eb5074df1b034b7b353a812af?sid=885691de-a28a-43ae-8981-6254312c9e53

**Comment by arpit1188** [comment]
Here is the actual issue showing as recording:

https://github.com/mixcore/mix.core/assets/124252403/240b1649-4823-4308-9657-99aa627013cb

**Comment by Smilefounder** [comment]
Hi @arpit1188 thanks for letting us know. We will take a look asap.
In the mean time, please also log an issue to Trumbowyg team as well. I think this might related ti Trumbowyg instead.

**Comment by arpit1188** [comment]
hello @Smilefounder, I already logged issue with [Trumbowyg](https://github.com/Alex-D/Trumbowyg/issues/1432) team.

**Comment by Smilefounder** [comment]
Hi @arpit1188 which mix version that you are using?

**Comment by develite98** [comment]
Hello @arpit1188, this is Trumbowyg's default behavior.
This document is available for viewing at [here](https://alex-d.github.io/Trumbowyg/documentation/#tags-to-keep.
)

We're working on an update, but if you need an urgent change, you can modify this file directly and restart the program (to obtain the correct configuration option, please refer to the [document](https://alex-d.github.io/Trumbowyg/documentation/#tags-to-keep)).

File path:  "**src\applications\Mixcore\wwwroot\mix-app\js\app-init.min.js**" - line **734**

**Comment by arpit1188** [comment]
> Hi @arpit1188 which mix version that you are using?
@Smilefounder 
"MixcoreVersion": "1.0.1"

**Comment by arpit1188** [comment]
Hello @develite98, As mentioned in documentation. I tried multiple things with different combination but its still not working.

I tried to change **svgPath = false** and tried **tagsToKeep** and also tried **semantic** properties.

**Comment by nhathoang989** [comment]
Hi @arpit1188 ,

You can try to add this script to portal/Index.cshtml

```
// Ref: https://stackoverflow.com/questions/49983637/prevent-svg-translation-of-fontawesome

// Notice how this gets configured before we load Font Awesome

<script type="text/javascript">
   window.FontAwesomeConfig = { autoReplaceSvg: false }
</script>
```


![image](https://github.com/mixcore/mix.core/assets/5327699/501254c4-fcb0-4cd9-a43f-b9ea6841b53c)

    
    Btw, you can also try to add this configuration to prevent trumbowysg from transforming your html tags 
    
    
![image](https://github.com/mixcore/mix.core/assets/5327699/4739a426-e106-4bc5-98be-e8a395cdaaa8)

**Comment by arpit1188** [comment]
@nhathoang989, Thanks its worked for me.
